
spring:
    application:
        name: echo-gateway

server:
    port: ${ECHO_GATEWAY_PORT:3030}

management:
    security:
        enabled: false

echo:
    gateway:
        core-pool-size: 2
        max-pool-size: 50
        queue-capacity: 10000
        fallback-title: "Uh oh"
        fallback-description: "Data could not be loaded due to a temporary problem. Try again later"
        default-page: 1
        efault-size: 20

eureka:
    client:
        serviceUrl:
            defaultZone: ${ECHO_REGISTRY_HOST:http://localhost:3036}/eureka/
    instance:
        leaseRenewalIntervalInSeconds: 1
        leaseExpirationDurationInSeconds: 2

ribbon:
    eureka:
        enabled: true
        MaxAutoRetries: 3
        MaxAutoRetriesNextServer: 1
        ReadTimeout: 1000
    #echo-catalog:
    #    listOfServers: echo-catalog,localhost:3031
    #echo-searcher:
    #    listOfServers: echo-searcher,localhost:3035

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 10000

feign:
    httpclient:
        connection-timeout: 5000
    hystrix:
        enabled: true
