
spring:
    application:
        name: echo-searcher

server:
    port: ${ECHO_SEARCHER_PORT:3035}
    undertow:
        worker-threads: 16

management:
    security:
        enabled: false

echo:
    searcher:
        default-page: 1
        default-size: 20
        core-pool-size: 16
        max-pool-size: 16
        queue-capacity: 10000
    benchmark:
        meter-interval: 200

eureka:
    client:
        serviceUrl:
            defaultZone: http://${ECHO_REGISTRY_HOST:127.0.0.1}:3036/eureka/
    instance:
        leaseRenewalIntervalInSeconds: 1
        leaseExpirationDurationInSeconds: 2

ribbon:
    eureka:
        enabled: true
        MaxAutoRetries: 3
        MaxAutoRetriesNextServer: 1
        ReadTimeout: 1000
    #echo-index:
    #    listOfServers: echo-index,localhost:3032

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 10000

feign:
    httpclient:
        connection-timeout: 5000
    hystrix:
        enabled: true
    registry-url: ${ECHO_REGISTRY_HOST:localhost}:${ECHO_REGISTRY_PORT:3036}
    index-url: ${ECHO_INDEX_HOST:localhost}:${ECHO_INDEX_PORT:3032}
