
spring:
    application:
        name: echo-searcher

server:
    port: 3035

management:
    security:
        enabled: false

echo:
    searcher:
        default-page: 1
        default-size: 20
        core-pool-size: 2
        max-pool-size: 50
        queue-capacity: 10000

feign:
    httpclient:
        connection-timeout: 5000
    hystrix:
        enabled: true

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 10000

ribbon:
    eureka:
        enabled: false
    echo-index:
        listOfServers: echo-index,localhost:3032
