
spring:
    application:
        name: echo-searcher
    cloud:
        consul:
            discovery:
                prefer-ip-address: true
            host: localhost
            port: 8500
            config:
                enabled: true
                watch:
                    enabled: true

server:
    port: 3035

management:
    security:
        enabled: false

echo:
    searcher:
        default-page: 1
        default-size: 20
        core-pool-size: 2
        max-pool-size: 50
        queue-capacity: 10000
    gateway:
        index-url: echo-index # TODO delete

feign:
    httpclient:
        connection-timeout: 5000
    hystrix:
        enabled: true

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 10000
