
spring:
    application:
        name: echo-registry

server:
    port: ${ECHO_REGISTRY_PORT:3036}
    undertow:
        worker-threads: 32

management:
    security:
        enabled: false
eureka:
    instance:
        hostname: echo-registry1
    client:
        registerWithEureka: false
        fetchRegistry: false
        service-url:
            defaultZone: http://localhost:${ECHO_REGISTRY_PORT:3036}/eureka
    server:
        enableSelfPreservation: false
