version: '2'
services:
    catalog-app:
        image: catalog
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://catalog-postgresql:5432/catalog
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    catalog-postgresql:
        extends:
            file: postgresql.yml
            service: catalog-postgresql
