version: '2'
services:
    echo-gateway:
        container_name: "echo-gateway"
        hostname: "echo-gateway"
        image: echo-gateway:latest
        #build: ../echo-microservices/app-gateway/Dockerfile
        ports:
            - 3030:3030
        environment:
            - ECHO_REGISTRY_HOST=echo-registry
            - ECHO_CATALOG_HOST=echo-catalog
            - ECHO_SEARCHER_HOST=echo-searcher
        links:
            - echo-catalog
            - echo-searcher
            - echo-registry
        depends_on:
            - echo-registry
    echo-catalog:
        container_name: "echo-catalog"
        hostname: "echo-catalog"
        image: echo-catalog:latest
        #build: ../echo-microservices/app-catalog/Dockerfile
        ports:
            - 3031:3031
        environment:
            - ECHO_RABBITMQ_HOST=echo-rabbitmq
            - ECHO_REGISTRY_HOST=echo-registry
        links:
            - echo-rabbitmq
            - echo-registry
        depends_on:
            - echo-rabbitmq
            - echo-registry
    echo-index:
        container_name: "echo-index"
        hostname: "echo-index"
        image: echo-index:latest
        #build: ../echo-microservices/app-index/Dockerfile
        ports:
            - 3032:3032
        volumes:
            - "/Users/max/volumes/echo/index"
        environment:
            - ECHO_RABBITMQ_HOST=echo-rabbitmq
            - ECHO_REGISTRY_HOST=echo-registry
        links:
            - echo-rabbitmq
            - echo-registry
        depends_on:
            - echo-rabbitmq
            - echo-registry
    echo-crawler:
        container_name: "echo-crawler"
        hostname: "echo-crawler"
        image: echo-crawler:latest
        #build: ../echo-microservices/app-crawler/Dockerfile
        ports:
            - 3033:3033
        environment:
            - ECHO_RABBITMQ_HOST=echo-rabbitmq
            - ECHO_REGISTRY_HOST=echo-registry
        links:
            - echo-rabbitmq
            - echo-registry
        depends_on:
            - echo-rabbitmq
            - echo-registry
    echo-parser:
        container_name: "echo-parser"
        hostname: "echo-parser"
        image: echo-parser:latest
        #build: ../echo-microservices/app-parser/Dockerfile
        ports:
            - 3034:3034
        environment:
            - ECHO_RABBITMQ_HOST=echo-rabbitmq
            - ECHO_REGISTRY_HOST=echo-registry
        links:
            - echo-rabbitmq
            - echo-registry
        depends_on:
            - echo-rabbitmq
            - echo-registry
    echo-searcher:
        container_name: "echo-searcher"
        hostname: "echo-searcher"
        image: echo-searcher:latest
        #build: ../echo-microservices/app-searcher/Dockerfile
        ports:
            - 3035:3035
        environment:
            - ECHO_REGISTRY_HOST=echo-registry
            - ECHO_INDEX_HOST=echo-index
        links:
            - echo-index

            - echo-registry
        depends_on:
            - echo-registry
            - echo-rabbitmq
    echo-registry:
        container_name: "echo-registry"
        hostname: "echo-registry"
        image: echo-registry:latest
        #build: ../echo-microservices/app-registry/Dockerfile
        ports:
            - 3036:3036
    echo-updater:
        container_name: "echo-updater"
        hostname: "echo-updater"
        image: echo-updater:latest
        #build: ../echo-microservices/app-updater/Dockerfile
        ports:
            - 3037:3037
        environment:
            - ECHO_RABBITMQ_HOST=echo-rabbitmq
            - ECHO_REGISTRY_HOST=echo-registry
        links:
            - echo-rabbitmq
            - echo-registry
        depends_on:
            - echo-rabbitmq
            - echo-registry
    echo-rabbitmq:
        container_name: "echo-rabbitmq"
        hostname: "echo-rabbitmq"
        image: rabbitmq:management
        ports:
          - "5672:5672"
          - "15672:15672"
