version: '2'
services:
    echo-gateway:
        container_name: "echo-gateway"
        hostname: "echo-gateway"
        image: echo-gateway:latest
        #build: ../echo-microservices/app-gateway/Dockerfile
        ports:
            - 3030:3030
        environment:
            - ECHO_REGISTRY_HOST=http://echo-registry:3036
        #    - ECHO_CONSUL_HOST=echo-consul
        links:
            - echo-catalog
            - echo-searcher
        #    - echo-consul
            - echo-registry
        depends_on:
        #     - echo-consul
            - echo-registry
    echo-catalog:
        container_name: "echo-catalog"
        hostname: "echo-catalog"
        image: echo-catalog:latest
        #build: ../echo-microservices/app-catalog/Dockerfile
        ports:
            - 3031:3031
        environment:
            - ECHO_RABBITMQ_HOST=echo-rabbitmq
            - ECHO_REGISTRY_HOST=http://echo-registry:3036
        #    - ECHO_CONSUL_HOST=echo-consul
        links:
        #    - echo-consul
            - echo-rabbitmq
            - echo-registry
        depends_on:
        #    - echo-consul
            - echo-rabbitmq
            - echo-registry
    echo-index:
        container_name: "echo-index"
        hostname: "echo-index"
        image: echo-index:latest
        #build: ../echo-microservices/app-index/Dockerfile
        ports:
            - 3032:3032
        volumes:
            - "/Users/max/volumes/echo/index"
        environment:
            - ECHO_RABBITMQ_HOST=echo-rabbitmq
            - ECHO_REGISTRY_HOST=http://echo-registry:3036
        #    - ECHO_CONSUL_HOST=echo-consul
        links:
        #    - echo-consul
            - echo-rabbitmq
            - echo-registry
        depends_on:
        #    - echo-consul
            - echo-rabbitmq
            - echo-registry
    echo-crawler:
        container_name: "echo-crawler"
        hostname: "echo-crawler"
        image: echo-crawler:latest
        #build: ../echo-microservices/app-crawler/Dockerfile
        ports:
            - 3033:3033
        environment:
            - ECHO_RABBITMQ_HOST=echo-rabbitmq
            - ECHO_REGISTRY_HOST=http://echo-registry:3036
        #    - ECHO_CONSUL_HOST=echo-consul
        links:
        #    - echo-consul
            - echo-rabbitmq
            - echo-registry
        depends_on:
        #    - echo-consul
            - echo-rabbitmq
            - echo-registry
    echo-parser:
        container_name: "echo-parser"
        hostname: "echo-parser"
        image: echo-parser:latest
        #build: ../echo-microservices/app-parser/Dockerfile
        ports:
            - 3034:3034
        environment:
            - ECHO_RABBITMQ_HOST=echo-rabbitmq
            - ECHO_REGISTRY_HOST=http://echo-registry:3036
        links:
        #    - echo-consul
            - echo-rabbitmq
            - echo-registry
        depends_on:
        #    - echo-consul
            - echo-rabbitmq
            - echo-registry
    echo-searcher:
        container_name: "echo-searcher"
        hostname: "echo-searcher"
        image: echo-searcher:latest
        #build: ../echo-microservices/app-searcher/Dockerfile
        ports:
            - 3035:3035
        environment:
        #    - ECHO_CONSUL_HOST=echo-consul
            - ECHO_REGISTRY_HOST=http://echo-registry:3036
        links:
            - echo-index
        #    - echo-consul
            - echo-registry
        depends_on:
            - echo-registry
        #    - echo-consul
            - echo-rabbitmq
    echo-registry:
        container_name: "echo-registry"
        hostname: "echo-registry"
        image: echo-registry:latest
        #build: ../echo-microservices/app-registry/Dockerfile
        ports:
            - 3036:3036
    #echo-consul:
    #    container_name: "echo-consul"
    #    hostname: "echo-consul"
    #    image: consul
    #    ports:
    #      - "8400:8400"
    #      - "8500:8500"
    #      - "8600:8600"
    echo-rabbitmq:
        container_name: "echo-rabbitmq"
        hostname: "echo-rabbitmq"
        image: rabbitmq:management
        ports:
          - "5672:5672"
          - "15672:15672"
