
server:
    port: ${ECHO_UPDATER_PORT:3037}
    undertow:
        worker-threads: 32

echo:
    updater:
        core-pool-size: 2
        max-pool-size: 50
        queue-capacity: 10000
    rabbit:
        updater-queue: echo.updater.queue
    amqp:
        exchange: echo.direct
        catalog-routingkey: echo.catalog.routingkey
        crawler-routingkey: echo.crawler.routingkey
        updater-routingkey: echo.updater.routingkey
    benchmark:
        meter-interval: 200

spring:
    application:
        name: echo-updater
    rabbitmq:
        host: ${ECHO_RABBITMQ_HOST:localhost}
        port: ${ECHO_RABBITMQ_PORT:5672}
        username: ${ECHO_RABBITMQ_USERNAME:guest}
        password: ${ECHO_RABBITMQ_PASSWORD:guest}

eureka:
    client:
        serviceUrl:
            defaultZone: http://${ECHO_REGISTRY_HOST:127.0.0.1}:3036/eureka/
    instance:
        leaseRenewalIntervalInSeconds: 1
        leaseExpirationDurationInSeconds: 2

feign:
    registry-url: ${ECHO_REGISTRY_HOST:localhost}:${ECHO_REGISTRY_PORT:3036}
