
spring:
    application:
        name: echo-index
    rabbitmq:
        host: ${ECHO_RABBITMQ_HOST:localhost}
        port: ${ECHO_RABBITMQ_PORT:5672}
        username: ${ECHO_RABBITMQ_USERNAME:guest}
        password: ${ECHO_RABBITMQ_PASSWORD:guest}

server:
    port: 3032

management:
    security:
        enabled: false

echo:
    index:
        lucene-path: /Users/max/volumes/echo/index
        core-pool-size: 2
        max-pool-size: 50
        queue-capacity: 10000

    rabbit:
        index-queue: echo.index.queue
    amqp:
        exchange: echo.direct
        index-routingkey: echo.index.routingkey
