version: '2'
services:
    gateway-app:
        image: gateway
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://gateway-postgresql:5432/gateway
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 3030:3030
    gateway-postgresql:
        extends:
            file: postgresql.yml
            service: gateway-postgresql
