
server:
    port: ${ECHO_CATALOG_PORT:3031}

spring:
    application:
        name: echo-catalog
    datasource:
        url: jdbc:h2:mem:echo
        username: sa
        password:
        driver-class-name: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate.ddl-auto: none
        show_sql: false
        properties:
            hibernate:
                show_sql: false
    h2:
        console:
            enabled: true
            path: /h2
    rabbitmq:
            host: ${ECHO_RABBITMQ_HOST:localhost}
            port: ${ECHO_RABBITMQ_PORT:5672}
            username: ${ECHO_RABBITMQ_USERNAME:guest}
            password: ${ECHO_RABBITMQ_PASSWORD:guest}

logging:
    level:
        org.hibernate.SQL: info

management:
    security:
        enabled:
            false

liquibase:
    change-log:
        classpath:db/liquibase/master.xml
    enabled: true
#liquibase.url=jdbc:h2:mem:echo
#liquibase.user=sa
#liquibase.password=

echo:
    catalog:
        default-page: 1
        default-size: 20
        core-pool-size: 2
        max-pool-size: 50
        queue-capacity: 10000
    rabbit:
        catalog-queue: echo.catalog.queue
    amqp:
        exchange: echo.direct
        catalog-routingkey: echo.catalog.routingkey
        crawler-routingkey: echo.crawler.routingkey
        index-routingkey: echo.index.routingkey

eureka:
    client:
        serviceUrl:
            defaultZone: http://${ECHO_REGISTRY_HOST:127.0.0.1}:3036/eureka/
    instance:
        leaseRenewalIntervalInSeconds: 1
        leaseExpirationDurationInSeconds: 2
