
server:
    port: ${ECHO_PARSER_PORT:3034}

echo:
    parser:
        core-pool-size: 2
        max-pool-size: 50
        queue-capacity: 10000
    rabbit:
        parser-queue: echo.parser.queue
    amqp:
        exchange: echo.direct
        parser-routingkey: echo.parser.routingkey
        catalog-routingkey: echo.catalog.routingkey

spring:
    application:
        name: echo-parser
    rabbitmq:
        host: ${ECHO_RABBITMQ_HOST:localhost}
        port: ${ECHO_RABBITMQ_PORT:5672}
        username: ${ECHO_RABBITMQ_USERNAME:guest}
        password: ${ECHO_RABBITMQ_PASSWORD:guest}

eureka:
    client:
        serviceUrl:
            defaultZone: ${ECHO_REGISTRY_HOST:http://localhost:3036}/eureka/
    instance:
        leaseRenewalIntervalInSeconds: 1
        leaseExpirationDurationInSeconds: 2

